apiVersion: v1
kind: Service
metadata:
  name: phoenix-faultlib
  namespace: phoenix-system
  labels:
    app: phoenix-faultlib
spec:
  selector:
    app: phoenix-faultlib
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
